[pytest]
# Enregistrement des marqueurs pour éviter les warnings
markers =
    unit: tests unitaires rapides et isolés.
    functional: tests d'intégration et de parcours utilisateur.
    load: tests de performance et de charge.

# Chemins de test par défaut
testpaths =
    test

# Dossiers d'importation
pythonpath = src